name: pdf_widget_wrapper
description: >
  Plugin that allows embedding of Flutter Widgets into a PDF document.
homepage: https://github.com/DavBfr/dart_pdf/tree/master/widget_wrapper
repository: https://github.com/DavBfr/dart_pdf
issue_tracker: https://github.com/DavBfr/dart_pdf/issues
version: 1.0.4
publish_to: none

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  pdf:
    git: https://github.com/kumsumit/pdf.git


dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
